/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.gui;

import co.edu.sena.data.Animal;
import co.edu.sena.data.HistorialClinico;
import co.edu.sena.data.Usuario;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Teleinformatica III
 */
public class VentanaHistorialClinico extends javax.swing.JFrame {
    private VentanaMenu menu;
    /**
     * Creates new form VentanaHistorialClinico
     */
    public VentanaHistorialClinico(VentanaMenu menu) {
        initComponents();
        this.menu=menu;
        Calendar hoy = Calendar.getInstance();
        mostrarFecha(hoy);
        mostrarConsecutivo();
        mostrarAnimales();
        mostrarUsuarios();
    }
    
    private void mostrarAnimales() {
        String [] data = new String[this.menu.getListaAnimales().size()];
        for (int i=0; i<this.menu.getListaAnimales().size(); i++) {
            Animal a = this.menu.getListaAnimales().get(i);
            data[i]=a.getCodigo()+"-"+a.getNombre();
        }
        txtAnimales.setModel(new DefaultComboBoxModel<String>(data));
    }
    
    private void mostrarUsuarios() {
        String [] data = new String[this.menu.getListaUsuarios().size()];
        for (int i=0; i<this.menu.getListaUsuarios().size(); i++) {
            Usuario u = this.menu.getListaUsuarios().get(i);
            data[i]=u.getNumeroIdentidad()+"-"+u.getNombres()+" "+u.getApellidos();
        }
        txtUsuarios.setModel(new DefaultComboBoxModel<String>(data));
    }
    
    private void mostrarConsecutivo() {
        lbConsecutivo.setText(""+(this.menu.getListaHistoriales().size()+1));
    }
    
    private void mostrarFecha(Calendar hoy) {
        int dia = hoy.get(Calendar.DAY_OF_MONTH);
        int mes = hoy.get(Calendar.MONTH);
        int anho = hoy.get(Calendar.YEAR);
        
        lbFecha.setText(dia+"/"+mes+"/"+anho);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbConsecutivo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnimales = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtProcedimeintos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarios = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Fecha");

        lbFecha.setText("jLabel2");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Consecutivo");

        lbConsecutivo.setText("jLabel3");

        jLabel3.setText("Animales");

        jLabel4.setText("Procedimientos");

        txtProcedimeintos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Parto", "Vacunación", "Control por crecimiento" }));

        jLabel5.setText("Usuarios");

        jLabel6.setText("Observaciones");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbFecha)
                            .addComponent(lbConsecutivo))
                        .addComponent(txtAnimales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProcedimeintos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbConsecutivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProcedimeintos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(68, 68, 68))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtProcedimeintos.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,"Debe seleccionar un procedimiento");
            txtProcedimeintos.requestFocus();
        } else {
            String fecha = lbFecha.getText();
            int consecutivo = Integer.parseInt(lbConsecutivo.getText());
            String codigoAnimal = ((String)txtAnimales.getSelectedItem()).split("-")[0];
            String procedimiento = (String) txtProcedimeintos.getSelectedItem();
            long idUsuario = Long.parseLong(((String)txtUsuarios.getSelectedItem()).split("-")[0]);
            String observaciones = txtObservaciones.getText();
            HistorialClinico clinico = new HistorialClinico(consecutivo, new Date(fecha), codigoAnimal, procedimiento, idUsuario, observaciones);
            this.menu.getListaHistoriales().add(clinico);
            limpiarCajas();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limpiarCajas() {
        txtObservaciones.setText(null);
        txtProcedimeintos.setSelectedIndex(0);
        txtAnimales.setSelectedIndex(0);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConsecutivo;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JComboBox<String> txtAnimales;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JComboBox<String> txtProcedimeintos;
    private javax.swing.JComboBox<String> txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
